[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''if os == 'OS X' or os == 'Windows' then'''
position = "at"
payload = '''if os == 'OS X' or os == 'Windows' or os == 'Linux' then'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''if os == 'OS X' then'''
position = "at"
payload = '''if os == 'OS X' or os == 'Linux' then'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''if love.system.getOS() == 'Windows' then'''
position = "at"
payload = '''if love.system.getOS() == 'Windows' or love.system.getOS() == 'Linux' then'''
overwrite = true
match_indent = true

# Enable Mobile UI (1.5x scale for some descriptions)

# [[patches]]
# [patches.pattern]
# target = "globals.lua"
# pattern = '''self.F_MOBILE_UI = false'''
# position = "at"
# payload = '''self.F_MOBILE_UI = true'''
# overwrite = true
# match_indent = true